
INSERT INTO vocabs (id, korean, japanese, english, polish)
VALUES

(10000,'さまざま, いろいろ','여러','several','kilka'),
(10001,'あらかじめ','미리','in advance','wcześniej'),
(10002,'勤勉する','부지런하다','Be diligent','ciężko pracować'),
(10003,'楽しむ','즐기다','enjoy','bawić się, cieszyć się'),
(10004,'順番で','차례대로','In turn, in order','po kolei'),
(10005,'文字','글자','letters','litery'),
(10006,'音感','음감','hearing sense','zmysł słuchu'),
(10007,'優れている','뛰어나다','outstanding','wybitny'),
(10008,'社交的','사교젹이다','sociable','towarzyski, społeczny'),
(10009,'手付きがよい','손재주가 좋다','good dexterity','mieć zręczne ręce'),
(10010,'才能','재주','skill','umiejętność'),
(10011,'説得力がある','설득력이 있다','persuasive','przekonujący'),
(10012,'物分りが速い','이해가 빠르다','quick to understand','szybko rozumieć'),
(10013,'責任感が強い','책임감이 강하다','strong sense of responsibility','silne poczucie odpowiedzialności'),
(10014,'手筋がいい','소질이있다','have a knack','Mieć talent, mieć zdolności'),
(10015,'進路をきめる','진로를 정하다','choose a career path','wybierać ścieżkę kariery'),
(10016,'適性に合っている','적성에 맞다','fit the aptitude','pasować do zdolności'),
(10017,'のどが チクチク する','목이 따끔거리다','sore throat','ból gardła'),
(10018,'決める','정하다','Choose','Wybierać'),
(10019,'専攻を生かす','전공을 살리다','Make the most of your major','wykorzystać swoją specjalizację'),
(10020,'実用的','실용적','useful','użyteczne'),
(10021,'肯定的','긍정적','positive','pozytywny,radosny'),
(10022,'喉が渇わく','목이마르다','thirsty','spragniony'),
(10023,'目がうす暗い','눈이 침침하다','eyes are dim','oczy są przyćmione'),
(10024,'首がごわつく','목이 뻣뻣하다','stiff neck','sztywny kark'),
(10025,'胃袋の調子が悪い','속이 거복하다','feel upset','czuć się zdenerwowanym'),
(10026,'胸苦しい','가슴이 답답하다','(feeling of) tightness in the chest','(uczucie) ucisku w klatce piersiowej'),
(10027,'胸焼けする','속이 쓰리다','feel upset','czuć się zdenerwowanym'),
(10028,'痒い','가렵다','itchy','swędzący'),
(10029,'蚊','모기','mosquito','komar'),
(10030,'窓','창문','window','okno'),
(10031,'総身','온몸','whole body','Całe ciało'),
(10032,'つばを飲込む','침을 삼키다','swallow saliva','połknąć ślinę'),
(10033,'借金','차금, 빚이','debt','dług'),
(10034,'影響','영향','effect','efekt'),
(10035,'寄生虫','기생충','parasite​','pasożyt'),
(10036,'足首','발목','ankle','kostka'),
(10037,'くじく','삐다','sprain','zwichnąć'),
(10038,'症状','증상','symptom','objaw, symptom'),
(10039,'整形外科','정형외과','Orthopedics','oddz. Ortopedyczny'),
(10040,'腫れる','붓다','swell','puchnąć'),
(10041,'生姜','생강','ginger','imbir'),
(10042,'残念ながら','아쉽게도','Unfortunately','Niestety'),
(10043,'遅刻','지각','lateness, tardiness','spóźnienie'),
(10044,'めまぐるしい','머리가 어지럽다','feel dizzy','mieć zawroty głowy'),
(10045,'泥棒','도둑','a thief','złodziej'),
(10046,'ぶつかり合あう','두딪치다','bump into','wpadać na coś'),
(10047,'相手側','상대편','the other side, the other party','druga strona, partner'),
(10048,'店を閉しめる, 門を打つ','문을 닫다','close the door, close business','zamknąć drzwi, zmknąć firmę'),
(10049,'床','바닥','floor','podłoga'),
(10050,'せつやくする','아끼다','economising','oszczędzać'),
(10051,'集まり, 集会','모임','meeting','spotkanie'),
(10052,'ずきずき痛む, しびれる','저리다','numb','zdrętwiały'),
(10053,'相変わらず, 依然として,今も変わらず','여전히','As usual, still,','Jak zwykle, nadal'),
(10054,'ふやける, ほとびる','봇다','see','zobaczyć'),
(10055,'間もなく, たった今, すぐ','금방','soon','wkrótce'),
(10056,'過ごす, 暮らす, 交わる','지내다','stay, live','zostać, żyć, przebywać'),
(10057,'ふさがる, 塞がる','막히다','blocked','zablokowany'),
(10058,'落とす, 失う, 逃がす','놓치다','to let go','odpuścić sobie, oswobodzić'),
(10059,'倒れる, 転ぶ, 敗れる','넘어지다','fall down','upaść'),
(10060,'はなはだしい, 激げしい, 厳びしい','심하다','Severe','ciężki, silny, poważny'),
(10061,'足の裏','발바닥','sole of foot​','dolna część stopy'),
(10062,'勧める','추천하다','recommend','polecać'),
(10063,'地面','땅자닥','ground','grunt'),
(10064,'注ぐ','쏟다','pour out, pour','wylać, nalać'),
(10065,'振う','다내다','run out','skończyć się'),
(10066,'汚い','더럽다','dirty','brudny'),
(10067,'凍る','얼다','freeze','zamrażać'),
(10068,'沸騰する','끓이다','boil','gotować'),
(10069,'毎晩','밤마다','every night','każda noc'),
(10070,'場所','장소','Place','Miejsce'),
(10071,'自分','자기','self','samego siebie'),
(10072,'筆箱','필통','pencilcase','piórnik'),
(10073,'職場','직장','rectal','odbytniczy'),
(10074,'選択','선택','select','wybierać'),
(10075,'理由','이유','Reason','Powód'),
(10076,'勤務','근무','work','Praca'),
(10077,'環境','환경','environment','środowisko'),
(10078,'卒業','졸업','Graduated','Absolwent'),
(10079,'就職','취직','find a job','Znajdź pracę'),
(10080,'ついに','드디어','finally','wreszcie'),
(10081,'作品','작품','Work','Praca'),
(10082,'性格','성격','personality','osobowość'),
(10083,'目がうす暗い','눈이 침침하다','my eyes are dim','moje oczy są przyćmione'),
(10084,'のどがひりひりする','목이 따끔거리다','sore throat','ból gardła'),
(10085,'首がごわつく','목이 뻣뻣하다','stiff neck','sztywna szyja, sztywny kark'),
(10086,'のどが渇く','목이 마르다','thirsty','spragniony'),
(10087,'胃袋の調子が悪い','속이 거복하다','feel upset,','czuć się zdenerwowanym, mieć wzdęty brzuch'),
(10088,'胸苦しい','가슴이 답답하다','have a heavy heart','ciężko na sercu'),
(10089,'腫れる','봇다','swell','spuchnąć'),
(10090,'痒い','가렵다','itchy','swędzenie'),
(10091,'窓','창문','window','okno'),
(10092,'総身','온몸','whole body','Całe ciało'),
(10093,'つばを飲込む','침을 삼키다','swallow saliva','połknąć ślinę'),
(10094,'油っこい','기름지다','oily','oleisty'),
(10095,'鼻をかむ','코를 풀다','blow nose','wydmuchać nos'),
(10096,'思い違える','오해하다','Misconceive, misunderstand','Źle zrozumieć'),
(10097,'消化','소화','digestion','trawienie'),
(10098,'足','다리','leg','noga'),
(10099,'歩く','걷다','To Walk','Chodzić'),
(10100,'過労','과로','strain','napięcie'),
(10101,'利益','이익','profit','zysk'),
(10102,'ゆっくり','편히','at ease, slowly','z łatwością, powoli'),
(10103,'論文','논문','thesis, paper, article​','Praca dyplomowa, praca naukowa'),
(10104,'美術','미술','Art','Sztuka'),
(10105,'男女老少','남녀노소','everyone','wszyscy(bez względu na wiek i płeć)'),
(10106,'豆腐','두부','tofu','tofu'),
(10107,'守る','지키다','Protect','Ochraniać'),
(10108,'大切','소중','precious','cenny'),
(10109,'若い','젊다','young','młody'),
(10110,'若者','젊은이','young people','młodzi ludzie'),
(10111,'不便','불편','Inconvenience','Niedogodność'),
(10112,'感動的','감동적이다','to be touched','być dotkniętym'),
(10113,'集中する','집중하다','Concentrate on','koncentrować się'),
(10114,'相手','상대','opponent','przeciwnik'),
(10115,'優勝','우승','Championship','Mistrzostwo'),
(10116,'負ける','지다','lose','stracić'),
(10117,'失礼','실례','discourtesy, impoliteness','ujma na honorze, niegrzeczność'),
(10118,'紅葉','단풍이','autumn leaves','jesienne liście'),
(10119,'合格','합격','pass','podawać'),
(10120,'交通','교통','traffic','ruch drogowy'),
(10121,'便利','편리하다','convenient','wygodny, prosty'),
(10122,'純真, 素直','숭진하다','to be noble','być szlachetnym'),
(10123,'今すぐ, 間もなく','금방','soon','wkrótce'),
(10124,'集まり , 集会','모임','class','klasa'),
(10125,'癪にさわる, 気にさわる','속상하다','upset','smutny'),
(10126,'ずきずき痛む, しびれる','저리다','numb','zdrętwiały'),
(10127,'ひざまずく, 膝をつく','무릎을 꿇다','kneel','klęczeć'),
(10128,'年が寄る,老ける','나이가 들다','getting old','starzeć się'),
(10129,'信ずる,信じる','믿다','believe','wierzyć'),
(10130,'親しい,近しい','친하다','close','bliski'),
(10131,'重要,大切','중요하다','It is important','To jest ważne'),
(10132,'カ, 蚊','모기','mosquito','komar'),
(10133,'傷つく,けがする, 痛める','다치다','get hurt','Zranić się'),
(10134,'長く,久しく','오래','long','długo'),
(10135,'ちゃんと,きちんと','제대로','properly','odpowiednio, porządnie'),
(10136,'過食,食べ過ぎ','과식','surfeit','przejedzenie'),
(10137,'過飲,飲過ぎ','과음','Overdrinking','Nadmierne picie'),
(10138,'過速,超過速度','과속','Speeding','Nadmierna prędkość'),
(10139,'過度な消費,過消費','과소비','overspending','nadmierne wydatki'),
(10140,'気にさわる, 気を病む','속상하다','upset','smutny'),
(10141,'別れる,離れる','헤어지다','break up, to part','zerwać, rozstać się, oddalić się'),
(10142,'昇進','승진','promotion','awans'),
(10143,'講義','강의','lecture','wykład'),
(10144,'職場','직장','one's post, workplace​','miejsce pracy'),
(10145,'逆に','오히려','conversely, on the contrary​','z drugiej strony'),
(10146,'選ばれる','뽑히다','be elected','być wybranym'),
(10147,'いびきをかく','코를 골다','snore','chrapać'),
(10148,'汗','땀','sweat','pot'),
(10149,'叔父','삼촌','uncle','wujek'),
(10150,'監督,マネージャー','감독','director, manager','dyrektor, reżyser'),
(10151,'尊敬','존경','respect','szacunek, poszanowanie'),
(10152,'干渉','간섭','Interference','Ingerencja, interwencja'),
(10153,'情報','정보','information','Informacja'),
(10154,'発表','발표','Announcement','Zapowiedź'),
(10155,'特徴','특징','Characteristic','Charakterystyka'),
(10156,'茶碗','찻잔','teacup','filiżanka do herbaty'),
(10157,'香 ','향','incense','kadzidło'),
(10158,'大陸','대륙','continent','kontynent'),
(10159,'会議','회의','meeting','spotkanie'),
(10160,'関連, 連関','관련','relation','relacja'),
(10161,'財産','재산','property','własność'),
(10162,'経済','경제','economy','gospodarka'),
(10163,'政治','정치','politics','Polityka'),
(10164,'化学','화학','chemistry','chemia'),
(10165,'言語,言葉','언어','language','język'),
(10166,'過ごす,暮らす','지내다','stay','zostać'),
(10167,'適応する','적응하다','It is adapted','Jest przystosowany'),
(10168,'秋','가을','autumn','jesień'),
(10169,'互いに,共に,お互いに','서로','each other','wzajemnie'),
(10170,'解決する','해결하다','solve','rozwiązywać'),
(10171,'解く','풀다','solve','rozwiązywać'),
(10172,'特徴','특징','Characteristic','Charakterystyka'),
(10173,'特色','특색','feature ','funkcja '),
(10174,'面接','면접','interview','rozmowa kwalifikacyjna, wywiad'),
(10175,'落ちる','떨어지다','fall down, fall, drop ','spaść, opuścić coś, padać'),
(10176,'苦しい,悩ましい,辛い','괴롭다','hard, difficult','ciężki, bolesny, '),
(10177,'静かに,ひっそり, ひそやかに','조용히','surreptitious​ly, quietly','cicho, spokojnie, dyskretnie'),
(10178,'放棄','포기','abandonment, resignation','porzucenie, zaniechanie'),
(10179,'恋人','연인','lover, boyfriend, girlfriend​','ukochany(a), sympatia'),
(10180,'会議','회의','meeting, conference','spotkanie'),
(10181,'開く, ,開ける','열리다','be open','być otwartym'),
(10182,'祝祭,お祭り,フェスティバル','축제','festival, feasts​','festyn, święto'),
(10183,'助言,口添え,アドバイス','조언','advice, counsel, suggestion, tip, hint​','rada, sugestia, podpowiedź'),
(10184,'常に,いつも,ふだん','항상','usually, always','zawsze, zwykle'),
(10185,'邪魔になる','방해가 되다','to become a hindrance, obstacle','przeszkadzać, blokować'),
(10186,'間違いなく,きっと','틀림없이','surely, for sure','na pewno, niewątpliwie'),
(10187,'高校, 高等学校','고등학교','high school','liceum'),
(10188,'同窓,どうそう ,同学','동창','fellow alumnus​','absolwent, (absolwent tej samej uczelni)'),
(10189,'指で示すこと','손가락질','finger pointing ','pokazywanie palcem'),
(10190,'交換する,取り替える,変更する','바꾼다','exchange','wymieniać'),
(10191,'指す, 指し示す','지적하다','Point out','wskazać'),
(10192,'材料','재료','material, ingredient','materiał, składnik'),
(10193,'当然,当たり前,もっとも','당연','Of course','oczywiście'),
(10194,'腹を立てる, 怒る','골을 내다','Get angry','Złościć się'),
(10195,'直接に, ,直直,直に','직접','directly','bezpośrednio'),
(10196,'確かだ,判然としている,知れた事','뻔하다','obvious','oczywisty, znany'),
(10197,'激怒する,かっとする','발끈하다','get furious','wściec się'),
(10198,'変動 ','변동','change, fluctuation​','zmiana, fluktuacja'),
(10199,'下級財,  下級品','열등재','inferior goods','towar niskiej jakości'),
(10200,'引き下げる, 値下げする','인하하다','to pull down, to lower, to reduce','ściągać opuszczać, zmniejszać'),
(10201,'先日','전날','the other day, a few days ago​','ostatnio, parę dni temu'),
(10202,'希望','희망','hope','nadzieja'),
(10203,'見積もり','견적','offer, estimation','oferta, wycena'),
(10204,'昨年, さくねん,  去年','작년','last year','ubiegły rok, zeszły rok'),
